# Generated by Django 5.1.2 on 2024-10-25 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_paid_pack_alter_student_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='validity_period',
            field=models.PositiveIntegerField(default=30, verbose_name='Термін дії (днів)'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понеділок'), (1, 'Вівторок'), (2, 'Середа'), (3, 'Четвер'), (4, "П'ятниця"), (5, 'Субота'), (6, 'Неділя')], verbose_name='День тижня')),
                ('start_time', models.TimeField(verbose_name='Час початку')),
                ('end_time', models.TimeField(verbose_name='Час закінчення')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='school.pack')),
            ],
            options={
                'verbose_name': 'Розклад',
                'verbose_name_plural': 'Розклади',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
