# Generated by Django 5.1.2 on 2024-10-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_pack_validity_period_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='course',
            field=models.ManyToManyField(to='school.course'),
        ),
    ]
