# Generated by Django 5.1.2 on 2024-10-26 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_lesson_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='course',
        ),
        migrations.AddField(
            model_name='pack',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school.course'),
        ),
    ]
