# Generated by Django 5.1.2 on 2024-10-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_student_slug_teacher_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='paid_pack',
        ),
        migrations.AddField(
            model_name='student',
            name='paid_pack',
            field=models.ManyToManyField(null=True, to='school.pack', verbose_name='Оплачений пакет'),
        ),
    ]
